# Generated by Django 4.0.5 on 2022-07-11 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rute_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveRequest',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('deleted', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=None, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_requested', to='rute_api.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
