# Generated by Django 4.0.5 on 2022-07-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rute_api', '0002_driverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[(1, 'waiting'), (2, 'validated'), (3, 'canceled')], default=1, max_length=64),
        ),
    ]
